version: '2'
services:

  nginx:
    build: nginx
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./:/usr/share/nginx/html

  php-fpm:
    image: nanoninja/php-fpm
    container_name: php-fpm
    volumes:
      - ./:/usr/share/nginx/html

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8080:80

  frontend:
    build: ./
    container_name: frontend
    volumes:
      - ./:/usr/share/frontend